# Generated by Django 5.1 on 2024-08-29 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_de_escolaridade', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('instituição', models.CharField(max_length=100)),
                ('preferencias', models.CharField(max_length=100)),
                ('habilidades', models.CharField(max_length=100)),
                ('experiência', models.TextField()),
                ('descricao', models.TextField()),
                ('projetos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Eu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('data_de_Nascimento', models.DateField()),
                ('genero', models.CharField(max_length=100)),
                ('estado_cívil', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('sobre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Meu_Blog_Pessoal.sobre')),
            ],
        ),
    ]
